### ISSUE TITLE
Writing Fields in Android

### ISSUE THREAD

**Issue by geokar2006** [kur0yama/Il2CppSDKGenerator#1]
I have a Class:
```c#
public class PlayerEnergy : MonoBehaviour
{
	public PlayerEnergy()
	{
	}
	public event Action<float> ikcacmgkmpm
	{
		add
		{
		}
		remove
		{
		}
	}
	public event Action jcfbonhdohn
	{
		add
		{
		}
		remove
		{
		}
	}
	public float ogajepabelo
	{
		get
		{
		}
		set
		{
		}
	}
	private void Awake()
	{
	}
	private void Start()
	{
	}
	private void Update()
	{
	}
	public static void ohclepekcnf(string inclnlnpecl = "NewTrigger", float kcbinhclndk = -0.01f)
	{
	}
	public static void jamblnifjbg(string inclnlnpecl)
	{
	}
	public static void djkmplmjjmd()
	{
	}
	public void OnEnergyChange(float value)
	{
	}
	public static bool eelljgbmfia()
	{
	}
	private static float plcjcknboea(float flfjndjkidf, int heonoknnoka)
	{
	}
	private static void ahhacobolhf(float jbbkedlmiob)
	{
	}
	private static void ojmmdeeaaha()
	{
	}
	public const float PLAYER_TABLETZOOMENERGY = -0.001624f;
	public const string PLYAER_TABLET = "Tablet";
	public static PlayerEnergy instance;
	public PlayerEnergy.EnergyTrigger EnergyTriggers;
	public List<GameObject> EnergyChangeRecivers;
	public bool Pause;
	protected float energy;
	private float pigfdhjaani;
	private bool ecmedhkhgap;
	private static Action<float> gfinmmjoild;
	private static Action nkeimpbjdlp;
	public class EnergyTrigger
	{
		public EnergyTrigger()
		{
		}
		public string Id;
		public float EnergyIncrese;
	}
}
```
I want to edit
```c#
protected float energy;
```
When I use this code:
```c++
PlayerEnergy::instance()->energy() = 1;
```
Android studio says it's an error to use" ->".
`member reference base type 'void' is not a structure or union`
What to do?

**Comment by geokar2006** [comment]
> Try to cast the instance to PlayerEnergy type.
> 
> ```c
> PlayerEnergy::instance<PlayerEnergy>()->energy() = 1;
> ```

Android studio again says that "- > " is incorrect and suggested using a dot. When I tried to check the energy in the game it froze.
Logcat says the game crashed.

**Comment by kur0yama** [comment]
Sorry I wrote wrong code, it should be 
```c
PlayerEnergy::instance<PlayerEnergy *>()->energy() = 1;
```
Also if another error occurs, please post the full error logs.

**Comment by geokar2006** [comment]
> Sorry I wrote wrong code, it should be
> 
> ```c
> PlayerEnergy::instance<PlayerEnergy *>()->energy() = 1;
> ```
> 
> Also if another error occurs, please post the full error logs.
Thank you it helped. But I have a question. Can I use functions from classes that don't have 
```c
static ClassName Instance;
 ```
?

**Comment by geokar2006** [comment]
And one more question. How do I call functions?

**Comment by geokar2006** [comment]
> > Sorry I wrote wrong code, it should be
> > ```c
> > PlayerEnergy::instance<PlayerEnergy *>()->energy() = 1;
> > ```
> > 
> > 
> > Also if another error occurs, please post the full error logs.
> 
> Thank you it helped. But I have a question. Can I use functions from classes that don't have
> 
> ```c
> static ClassName Instance;
> ```
> 
> ?

I'll deal with this later.  I have another question, but it's better to make a separate issue for it.
